name: Build
# From now in android
# https://github.com/android/nowinandroid

on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - uses: ./.github/actions/setup-java

      - name: Check lint
        run: ./gradlew lintDebug --stacktrace

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: lint-reports
          path: build/lint-reports

      - name: Build all build type and flavor permutations
        run: ./gradlew assemble --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: build-outputs
          path: app/build/outputs

#  androidTest:
#    needs: build
#    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
#    timeout-minutes: 45
#    strategy:
#      matrix:
#        api-level: [ 23, 26, 30 ]
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Copy CI gradle.properties
#        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v1
#        with:
#          java-version: 17
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#
#      - name: Run instrumentation tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: ${{ matrix.api-level }}
#          arch: x86_64
#          disable-animations: true
#          disk-size: 1500M
#          heap-size: 512M
#          script: ./gradlew connectedDebugAndroidTest
#
#      - name: Upload test reports
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-reports
#          path: '*/build/reports/androidTests'
