name: Build
# From now in android
# https://github.com/android/nowinandroid

on:
  push:
    branches:
      - main
      - tomoya0x00/add_stage_push_workflow
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: ./.github/actions/setup-java

      - name: Build all build type and flavor permutations
        run: ./gradlew assemble --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: build-outputs
          path: app-android/build/outputs
          retention-days: 14

#  androidTest:
#    needs: build
#    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
#    timeout-minutes: 45
#    strategy:
#      matrix:
#        api-level: [ 23, 26, 30 ]
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Copy CI gradle.properties
#        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v1
#        with:
#          java-version: 17
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#
#      - name: Run instrumentation tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: ${{ matrix.api-level }}
#          arch: x86_64
#          disable-animations: true
#          disk-size: 1500M
#          heap-size: 512M
#          script: ./gradlew connectedDebugAndroidTest
#
#      - name: Upload test reports
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-reports
#          path: '*/build/reports/androidTests'
