name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ios-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ios:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Select Xcode
        run: sudo xcode-select -s '/Applications/Xcode_15.0.app'

      - uses: ./.github/actions/setup-java

      - name: Set up Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          bundler-cache: true

      - name: Set up XCFramework arch filter
        run: echo "arch=x86_64" >> local.properties

      - name: Build KMM Module
        uses: gradle/gradle-build-action@243af859f8ca30903d9d7f7936897ca0358ba691 # v2
        with:
          gradle-home-cache-cleanup: true
          arguments: :app-ios-shared:assembleSharedReleaseXCFramework --stacktrace

      - name: Build App
        working-directory: app-ios
        run: bundle exec fastlane build_project
